### ISSUE TITLE
reached the type-length limit while instantiating

### ISSUE THREAD

**Issue by gaproman** [jrasky/corepack#11]
Trying to compile this code
```
#[macro_use]
extern crate serde_derive;
extern crate corepack;

use corepack::to_bytes;

#[derive(Serialize)]
pub enum TreeElement {
    Value(u64),
    Node(Vec<TreeElement>)
}

fn main() {
    let n = TreeElement::Node(vec![]);
    let f = to_bytes(n);
    print!("{:?}", f);
}
```

I received an error: `reached the type-length limit while instantiating <corepack::Serializer<F>><[closure@DefId(11/1:54 ~ corepack[8323...`

Increasing of the type_length_limit parameter doesn't solve the problem.
It seems that corepack doesn't support recursive data structures.

**Comment by gaproman** [comment]
Any ideas on how to fix it?

**Comment by cbeck88** [comment]
Does messagepack support recursive data structures?

Edit: I guess you are right, it should work, I guess it's a limitation of corepack

**Comment by jrasky** [comment]
This issue is super old, and the next steps on corepack are to update it since I last worked on it two years ago. If this is still a problem, please re-open this issue.
