### ISSUE TITLE
Update to serde 0.9.0

### ISSUE THREAD

**Issue by dtolnay** [jrasky/corepack#3]
https://github.com/serde-rs/serde/releases/tag/v0.9.0

The release supports no_std in a much better way, both for error messages and for `#[derive(Serialize, Deserialize)]`.

**Comment by jrasky** [comment]
That's awesome! Unfortunately, it seems they've broken their api again, so it'll take some work to go through and fix everything. I'll get on it next week, probably.

**Comment by astraw** [comment]
@jrasky I am interested in your fixes and would be happy to test.

**Comment by jrasky** [comment]
sorry this is taking a while, I've been very busy. I might have some time tomorrow to get some work in on this.

**Comment by astraw** [comment]
It [doesn't look so simple](https://github.com/pyfisch/cbor/commit/38589873e38970040f2672c826795a4f6ccaec63). I can understand if it takes a while. I am also quite busy, otherwise I would try to do it myself.

**Comment by jrasky** [comment]
I've put some work in, and I have things broken but compiling on newer serde. I'll keep working on things to iron out the remaining issues and make things more readable.

**Comment by jrasky** [comment]
I've done the work for the upgrade, take a look at #4

**Comment by astraw** [comment]
Thanks, that's great. I'm afraid it may be a while before I can check this, but I'll do my best, as I am very interested.

**Comment by jrasky** [comment]
Just merged #4
